# Titanic Model
## Paso 1: Cargar biblioteca.

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
import pandas as pd

## Paso 2: Cargar y preparar los datos.

In [4]:
df = pd.read_csv('titanic.csv')

In [5]:
df.head()

   sobrevivio  clase  genero  edad  hermanos_conyuges  padres_hijos
0           0      3  hombre    22                  1             0
1           1      1   mujer    38                  1             0
2           1      3   mujer    26                  0             0
3           1      1   mujer    35                  1             0
4           0      3  hombre    35                  0             0

In [6]:
df.tail()

     sobrevivio  clase  genero  edad  hermanos_conyuges  padres_hijos
709           0      3   mujer    39                  0             5
710           0      2  hombre    27                  0             0
711           1      1   mujer    19                  0             0
712           1      1  hombre    26                  0             0
713           0      3  hombre    32                  0             0

In [7]:
df['genero'] = df['genero'].map({'hombre': 0, 'mujer': 1})

In [8]:
df.head()

   sobrevivio  clase  genero  edad  hermanos_conyuges  padres_hijos
0           0      3       0    22                  1             0
1           1      1       1    38                  1             0
2           1      3       1    26                  0             0
3           1      1       1    35                  1             0
4           0      3       0    35                  0             0

## Paso 3: Separar de predictores y objetivos.

In [9]:
X = df.drop(columns='sobrevivio')

In [10]:
X.head()

   clase  genero  edad  hermanos_conyuges  padres_hijos
0      3       0    22                  1             0
1      1       1    38                  1             0
2      3       1    26                  0             0
3      1       1    35                  1             0
4      3       0    35                  0             0

In [11]:
y = df['sobrevivio']

In [12]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: sobrevivio, dtype: int64

## Paso 4: Dividir en entrenamiento y prueba a nuestros datos

In [13]:
predictorX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)